- name: openvpn | host tun tap
  hosts: openvpn
  become: yes
  vars:
    linkmode: tun
  tasks:
    - name: update
      apt:
        update_cache=yes
      tags:
        - update apt

    - name: Install tools
      apt:
        name: 
          - openvpn
          - iperf3
          - selinux-utils
        state: present
        update_cache: true

    - name: keygen
      ansible.builtin.shell: |
        openvpn --genkey secret /etc/openvpn/static.key
      when: (ansible_hostname == "server")

    - name: Copy key file
      fetch:
        src: /etc/openvpn/static.key
        dest: /tmp/
        flat: yes
      when: (ansible_hostname == "server")

    - name: Copy key file client
      copy:
        src: /tmp/static.key
        dest: /etc/openvpn/static.key
        mode: 0644
        owner: root
        group: root
      when: (ansible_hostname == "client")

    - name: Copy server config file
      template:
        remote_src: false
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "{{ item.mode }}"
      with_items:
        - { src: "ansible/templates/server1.conf", dest: "/etc/openvpn/server.conf", mode: "0644" }
        - { src: "ansible/templates/openvpn@.service", dest: "/etc/systemd/system/openvpn@.service", mode: "0644" }
      when: (ansible_hostname == "server")
      tags:
        - linkmode

    - name: Copy client config file
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "{{ item.mode }}"
      with_items:
        - { src: "ansible/templates/server2.conf", dest: "/etc/openvpn/server.conf", mode: "0644" }
        - { src: "ansible/templates/openvpn@.service", dest: "/etc/systemd/system/openvpn@.service", mode: "0644", }
      when: (ansible_hostname == "client")
      tags:
        - linkmode

    - name: Enabled openvpn service
      service:
        name: openvpn
        state: started
        enabled: true

    - name: Restart openvpn service
      service:
        name: openvpn
        state: restarted
      tags:
        - linkmode

    - name: restart hosts
      reboot:
        reboot_timeout: 200